version: '3.8'

services:
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #   ports:
  #     - "3307:3306"
  #     - "3306:3306"

  #     - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      DATABASE_URL: mysql://agendamento_salas:admin@cloud.fslab.dev:8806/agendamento_salas
      SWAGGER_DEV_URL: http://localhost:3000
    ports:
      - "3000:3000"
    # depends_on:
    #   - db

# volumes:
#   mysql-data:
