apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ensalamento-api
  name: ensalamento-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ensalamento-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ensalamento-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env:
            - name: DATABASE_URL
              value: mysql://agendamento_salas:admin@cloud.fslab.dev:8806/agendamento_salas
            - name: JWT_SECRET
              value: secretKey
            - name: PORT
              value: "3000"
            - name: SWAGGER_PROD_URL
              value: https://ensalamento-api.app.fslab.dev
          image: registry.fslab.dev/visualizacao-sala/api:latest
          name: ensalamento-api
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ensalamento-api
  name: ensalamento-api
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: ensalamento-api
